packages_for_install <- c("skimr",
                          "tidyverse",
                          "modeltime",
                          "tidymodels",
                          "workflowsets",
                          "timetk",
                          "xgboost",
                          "randomForest",
                          "caret",
                          "lubridate",
                          "devtools",
                          "plotly",
                          "shiny",
                          "openxlsx",
                          "writexl",
                          "dendextend")

install.packages(setdiff(packages_for_install,
                         rownames(installed.packages())),
                 repos = "http://cran.us.r-project.org")
